name: NinCore
version: ${project.version}
main: me.ninjoh.nincore.NCNinCore
author: Ninjoh
commands:
   nincore:
     aliases: [nc]
permissions:
    nincore.*:
        description: Gives access to all nincore permissions & commands.
        children:
            nincore.getjavaversion: true
            nincore.isansiconsole: true
    nincore.getjavaversion:
        default: op
    nincore.isansiconsole:
        default: op